#
# INTEL CONFIDENTIAL
# Copyright (c) 2018 Intel Corporation
#
# The source code contained or described herein and all documents related to
# the source code ("Material") are owned by Intel Corporation or its suppliers
# or licensors. Title to the Material remains with Intel Corporation or its
# suppliers and licensors. The Material contains trade secrets and proprietary
# and confidential information of Intel or its suppliers and licensors. The
# Material is protected by worldwide copyright and trade secret laws and treaty
# provisions. No part of the Material may be used, copied, reproduced, modified,
# published, uploaded, posted, transmitted, distributed, or disclosed in any way
# without Intel's prior express written permission.
#
# No license under any patent, copyright, trade secret or other intellectual
# property right is granted to or conferred upon you by disclosure or delivery
# of the Materials, either expressly, by implication, inducement, estoppel or
# otherwise. Any license under such intellectual property rights must be express
# and approved by Intel in writing.
#

import yaml
import os
import shutil
from typing import Tuple

from util.logger import initialize_logger


log = initialize_logger('packs.tf_training')

import packs.common as common

def update_configuration(experiment_folder: str, script_location: str,
                         script_folder_location: str,
                         script_parameters: Tuple[str, ...]) -> int:
    """
    Updates configuration of a tf-training pack based on paramaters given by a user.

    The following files are modified:
    - Dockerfile - name of a training script is replaced with the one given by a user
                 - all additional files from experiment_folder are copied into an image
                   (excluding files generated by draft)
    - charts/templates/job.yaml - list of arguments is replaces with those given by a user

    :return:
    - exit_code - 0 if configuration was updated correctly, 1 otherwise
    """
    log.debug("Update configuration - start")
    try:
        modify_job_yaml(experiment_folder, script_location, script_parameters)
        modify_dockerfile(experiment_folder)
    except Exception as exe:
        log.error("Update configuration - i/o error : {}".format(exe))
        return 1

    log.debug("Update configuration - end")
    return 0

def modify_dockerfile(experiment_folder: str):
    log.debug("Modify dockerfile - start")
    dockerfile_name = os.path.join(experiment_folder, "Dockerfile")
    dockerfile_temp_name = os.path.join(experiment_folder, "Dockerfile_Temp")
    dockerfile_temp_content = ""

    with open(dockerfile_name, "r") as dockerfile:
        for line in dockerfile:
            if line.startswith("ADD training.py"):
                dockerfile_temp_content =  dockerfile_temp_content + common.prepare_list_of_files(experiment_folder)
            else:
                dockerfile_temp_content = dockerfile_temp_content + line

    with open(dockerfile_temp_name, "w") as dockerfile_temp:
        dockerfile_temp.write(dockerfile_temp_content)

    shutil.move(dockerfile_temp_name, dockerfile_name)
    log.debug("Modify dockerfile - end")

def modify_job_yaml(experiment_folder: str, script_location: str, script_parameters: Tuple[str, ...]):
    log.debug("Modify job yaml - start")
    job_yaml_filename = os.path.join(experiment_folder, "charts//tf-training//values.yaml")
    job_yaml_temp_filename = os.path.join(experiment_folder, "charts//tf-training//values_temp.yaml")

    with open(job_yaml_filename, "r") as job_yaml_file:
        y = yaml.load(job_yaml_file)
        y["commandline"]["args"] = common.prepare_script_paramaters(script_parameters, script_location)

    with open(job_yaml_temp_filename, "w") as job_yaml_file:
        yaml.dump(y, job_yaml_file)

    shutil.move(job_yaml_temp_filename, job_yaml_filename)
    log.debug("Modify job yaml - end")
