apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "fullname" . }}-postgres
  labels:
    app: {{ template "postgresql.name" . }}
    chart: gitea
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.persistence.annotations }}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
{{- end }}

spec:
  capacity:
    storage: {{ .Values.persistence.postgresSize | quote }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/Master
          operator: In
          values:
          - "True"
  hostPath:
    path: "/data/{{ .Release.Name }}/postgres"
    type: DirectoryOrCreate
