FROM 'registry.toolbox.nervana.sclab.intel.com:80/dls4e/shared/centos:3c416291150d6d7a5e6272cc3086916f049ce8bd'
#FROM centos:latest

ARG no_proxy=os.mirror
ARG https_proxy=http://proxy-chain.intel.com:911
ARG http_proxy=http://proxy-chain.intel.com:911

RUN yum install socat -y
RUN yum install bind-utils -y
COPY socat_script.sh /usr/bin/
RUN chmod 0777 /usr/bin/socat_script.sh
