---

- name: "{{ message_label }} Create required groups for cluster facts synchronization"
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
  with_items:
    - name: cluster-facts
      gid: 3510

- name: "{{ message_label }} Ensure that home dir exists"
  file:
    path: /opt/nauta/home
    state: directory
    mode: 0755
    owner: root
    group: root

- name: "{{ message_label }} Create required users for cluster synchronization"
  user:
    name: "{{ item.name }}"
    create_home: True
    generate_ssh_key: True
    groups: cluster-facts
    uid: "{{ item.uid }}"
    home: "/opt/nauta/home/{{ item.name }}"
  with_items:
    - name: cluster-facts
      uid: 3510

- include_tasks: include_distribution.yml
  vars:
    distribution_file: install.yml

- name: "{{ message_label }} Fetch public keys from hosts"
  slurp:
    src: "/opt/nauta/home/cluster-facts/.ssh/id_rsa.pub"
  register: cluster_facts_key

- name: "{{ message_label }} Add authorized master keys to facts users"
  authorized_key:
    user: cluster-facts
    key: "{{ hostvars[item].cluster_facts_key.content | b64decode }}"
  with_items: "{{ groups['master'] }}"

- name: "{{ message_label }} Render facts key config"
  template:
    src: config.j2
    dest: /opt/nauta/home/cluster-facts/.ssh/config
    mode: 0600
    owner: cluster-facts
    group: cluster-facts
  when: inventory_hostname in groups['master']

- name: "{{ message_label }} Create cluster directory"
  file:
    path: /etc/nauta-facts
    state: directory
    owner: cluster-facts
    group: cluster-facts
    mode: 0750
