---

- include_tasks: include_distribution.yml
  vars:
    distribution_file: install.yml

- name: "{{ message_label }} Prepare sysctl configuration"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - name: net.ipv4.ip_forward
      value: 1
    - name: net.ipv4.ip_nonlocal_bind
      value: 1

- name: "{{ message_label }} Render nginx config"
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - Restart Nginx

- name: "{{ message_label }} Create service configuration path"
  file:
    path: /etc/systemd/system/nginx.service.d
    state: directory

- name: "{{ message_label }} Render proxy configuration"
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/systemd/system/nginx.service.d/{{ item }}.conf"
  with_items:
    - consul
  notify:
    - Reload Systemd
    - Restart Nginx

- name: "{{ message_label }} Create nginx config dirs"
  file:
    path: "/etc/nginx/{{ item }}.d"
    state: directory
  with_items:
    - http
    - stream

- name: "{{ message_label }} Render stream dirs"
  template:
    src: "{{ item }}.stream.j2"
    dest: "/etc/nginx/stream.d/{{ item }}.conf"
  with_items:
    - apiservice
    - ingress
    - samba
  notify:
    - Restart Nginx

- name: "{{ message_label }} Render http dirs"
  template:
    src: "{{ item }}.http.j2"
    dest: "/etc/nginx/http.d/{{ item }}.conf"
  with_items:
    - ingress
  notify:
    - Restart Nginx

- meta: flush_handlers

- name: "{{ message_label }} Start and enable nginx"
  service:
    name: nginx
    state: started
    enabled: True
