---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-user"
  labels:
    app: "{{ .Release.Name }}-user"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{ .Values.api_group_name }}/dls: "true"
rules:
- apiGroups:
    - "*"
  resources:
    - pods/portforward
  verbs:
    - list
    - get
    - create
