apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-{{ .Release.Namespace }}-input
  labels:
    kind: internal
    type: input
    app: samba
spec:
  accessModes:
  - ReadWriteMany
  - ReadWriteOnce
  capacity:
    storage: 32Gi
  nfs:
    path: {{ .Values.input }}
    server: {{ .Values.ip }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
